# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dates.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 609)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(450, 10, 351, 521))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.dates = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.dates.setFont(font)
        self.dates.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.dates.setStyleSheet("color:rgb(100,100,100);")
        self.dates.setAlignment(QtCore.Qt.AlignCenter)
        self.dates.setObjectName("dates")
        self.verticalLayout.addWidget(self.dates)
        self.event = QtWidgets.QTextEdit(self.layoutWidget)
        self.event.setObjectName("event")
        self.verticalLayout.addWidget(self.event)
        self.update = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.update.setFont(font)
        self.update.setStyleSheet("border:3px solid rgb(0,0,0);\n"
"background-color: rgb(130,130,130);\n"
"color:rgb(255,255,255);")
        self.update.setObjectName("update")
        self.verticalLayout.addWidget(self.update)
        self.add = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.add.setFont(font)
        self.add.setStyleSheet("border:3px solid rgb(0,0,0);\n"
"background-color: rgb(130,130,130);\n"
"color:rgb(255,255,255);")
        self.add.setObjectName("add")
        self.verticalLayout.addWidget(self.add)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 30, 441, 521))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.exit = QtWidgets.QPushButton(self.centralwidget)
        self.exit.setGeometry(QtCore.QRect(0, 550, 801, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.exit.setFont(font)
        self.exit.setStyleSheet("border:3px solid rgb(0,0,0);\n"
"background-color: rgb(130,130,130);\n"
"color:rgb(255,255,255);\n"
"")
        self.exit.setObjectName("exit")
        self.calendar = QtWidgets.QCalendarWidget(self.centralwidget)
        self.calendar.setGeometry(QtCore.QRect(10, 10, 439, 519))
        self.calendar.setStyleSheet("")
        self.calendar.setObjectName("calendar")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.dates.setText(_translate("MainWindow", "Заплановані дати"))
        self.update.setText(_translate("MainWindow", "Завантажити"))
        self.add.setText(_translate("MainWindow", "Додати"))
        self.exit.setText(_translate("MainWindow", "Вихід"))
